default_language_version:
    python: python3
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit hooks
    autofix_prs: true
    autoupdate_branch: 'pre-commit-autoupdate'
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: [no-commit-to-branch]
    submodules: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: 'meta.yaml'
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: '\.(rst|txt)$'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        name: Prevent Commit to Main Branch
        args: ["--branch", "main"]
        stages: [pre-commit]
